name: GitHub Actions run script
run-name: ${{ github.actor }} is running script.py 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: pip3 install -U pyrogram # Install the dependencies (if needed)

      - name: Execute Python script # Run the script.py file to get the latest data
        run: python script.py
