name: GitHub Actions run script
run-name: ${{ github.actor }} is running script.py 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        run: sudo apt install python3
      - name: Install pyrogram
        run: pip3 install -U pyrogram
        run: ls /metelyk-userbot-A1
      - name: Run script
        run: python script.py
